### ISSUE TITLE
[Harry Potter] Lieux

### ISSUE THREAD

**Issue by SuceMaLicorne** [Volminoduro/le-compendium#3]
# **1. Soins**
**1.1. Taverne de la Tête du Sanglier**
>Quid des échanges si plusieurs personnes ? Interférer ? Annuler ? Reporter après combat ?

**1.2. Hôpital Ste-Mangouste**
Cool ++

# **2. Récupération de cartes**
Guipure et Tissard & Brodette
> Tissard & Brodette : Devient peu intéressant en fin de partie. 
Moyen de pallier à ça pour ne pas que la case devienne fantôme (?)

**2.3. Boutique de Fred et Georges**
>Dragée sur score 6 : Risque de snowball ?

>Dragée sur score 7 : Que faire pour éviter le spam du 7 par chance ou avec items et compétences influençant les jets de dés (?)

#** 3. Equipements**
**3.2. Gregorovith Zauberstäbe**
> Fonction un peu trop simple (?) Rajouter un effet supplémentaire ? Quitte à nerf le premier au besoin.

# **4. Evènements**
**4.1. La Forêt Interdite** 
3 - Ford Anglia détraquée > _"Si vous avez fait 7, la Ford Anglia vous emmène à la case adjacente du Lieu de votre choix"._
Il suffit de demander la case adjacente au réel choix et 1/2 de tomber sur notre réel choix > à revoir (?).

5 - Gibier : vous pouvez attaquer, si vous faites plus de 2, guérissez-vous d’une blessure.
> Quel dé (?)

7 - Touffu [Un peu trop fort ?] : 
> _"Vous êtes mort, mort et remort"_
à voir à quel point tu veux pouvoir être néfaste et/ou décisif sur la RNG. 
> Quel dé (?)

**4.2. Azkaban**
> Triple punition: Tour bloqué + destruction de la main + destruction du stuff
Comme pour Touffu > Décisif (?)

**4.3. Salle de la coupe de feu**
_"La coupe sélectionne aléatoirement un personnage de chaque alignement disponible."_
Dévoilement de l'alignement > Volontaire (?) les joueurs doivent ils se présenter pour être tiré au sort et être dévoilés ?
> Quid si un joueur est à 3 PV et rush la coupe seul (?) événement a t-il lieu (?)
Si oui, peut permettre d'éviter le snowball, cool ++

**4.4. Tribunal magique**
Joue sur la mécanique de dévoilement de la quête, cool +

**4.5. Poudlard Express**
> Rendre la rencontre avec les détraqueurs aléatoire ?
> Intérêt d'aller sur la case si c'est que du malus (?) - Pouvoir se TP case de son choix T+1 ?

**4.6. L’allée des embrumes**
> Un poil trop "fort" visé peut être l'item le plus OP ou jet de dé, X item jeté 

# **5. Autres**
**5.1. La salle sur demande**
Carte terrain déjà passées ? Cartes encore dans la pioche (nécessite connaissance du jeu) > compliqué.
> Reproduire une carte terrain en jeu (?)

**Comment by Volminoduro** [comment]
# **1. Soins**
**1.1. Taverne de la Tête du Sanglier**
>Quid des échanges si plusieurs personnes ? Interférer ? Annuler ? Reporter après combat ?

Les échanges s'auto-organisent par les joueurs. Tel que cela se déroulerait normalement lorsqu'on ramasse une carte. Il n'est pas possible de s'y battre.

# **2. Récupération de cartes**
Guipure et Tissard & Brodette (TODO)
> Tissard & Brodette : Devient peu intéressant en fin de partie. 
Moyen de pallier à ça pour ne pas que la case devienne fantôme (?)

#** 3. Equipements**
**3.2. Gregorovith Zauberstäbe** (TODO)
> Fonction un peu trop simple (?) Rajouter un effet supplémentaire ? Quitte à nerf le premier au besoin.

# **4. Evènements**
**4.1. La Forêt Interdite** 

Il ne faut pas oublier que l'on peut demander son aide dans ce lieu, comme dans Munchkin.

**4.2. Azkaban**
> Triple punition: Tour bloqué + destruction de la main + destruction du stuff

le tour n'est plus bloqué.

**4.3. Salle de la coupe de feu**
_"La coupe sélectionne aléatoirement un personnage de chaque alignement disponible."_
Dévoilement de l'alignement > Volontaire (?) les joueurs doivent ils se présenter pour être tiré au sort et être dévoilés ?
> Quid si un joueur est à 3 PV et rush la coupe seul (?) événement a t-il lieu (?)
Si oui, peut permettre d'éviter le snowball, cool ++

La coupe de feu nécessite au minimum trois joueurs pour se faire.

**4.5. Poudlard Express** (TODO)
> Rendre la rencontre avec les détraqueurs aléatoire ?

C'est purement un malus. Il me faut une autre histoire pour cette case mais avec des effets proches, afin que l'utilisation de la Poudre d'obscurité Instantané du Perou soit RP.

**4.6. L’allée des embrumes**
> Un poil trop "fort" visé peut être l'item le plus OP ou jet de dé, X item jeté 

J'ai mis que les 3 objets de plus grande qualité, dans l'ordre décroissant.

**Comment by Volminoduro** [comment]
# **2. Récupération de cartes**
Guipure et Tissard & Brodette (TODO)
> Tissard & Brodette : Devient peu intéressant en fin de partie. 
Moyen de pallier à ça pour ne pas que la case devienne fantôme (?)

# **3. Equipements**
**3.2. Gregorovith Zauberstäbe** (TODO)
> Fonction un peu trop simple (?) Rajouter un effet supplémentaire ? Quitte à nerf le premier au besoin.

# **4. Autres**
**4.5. Poudlard Express** (Corrigé)
> Rendre la rencontre avec les détraqueurs aléatoire ?

Remplacé par la Forêt de Dean. Même effet, juste contexte narratif différent.

**Comment by Volminoduro** [comment]
# **2. Récupération de cartes**
Guipure et Tissard & Brodette (TODO)
> Tissard & Brodette : Devient peu intéressant en fin de partie. 
Moyen de pallier à ça pour ne pas que la case devienne fantôme (?)

=> Pour l'instant, je me restreins à 18 Lieux, donc j'ai décidé d'enlever ce lieu. Peut-être pour une prochaine extension.

# **3. Equipements**
**3.2. Gregorovith Zauberstäbe** (TODO)
> Fonction un peu trop simple (?) Rajouter un effet supplémentaire ? Quitte à nerf le premier au besoin.

Les nouveaux effets sont : 
* Vous permet de regagner jusqu'à 1 charge sur l'équipement de votre choix.
* Vous pouvez regagner 1 charge supplémentaire pour 1 points d'équipement, utilisable plusieurs fois sur plusieurs équipements.
* Vous ne pouvez tenter cette action que si vous êtes le premier à le faire : si la _Baguette de Sureau_ n'est pas en possession d'un joueur, vous pouvez tenter d'attaquer Gregorovitch. Si le résultat est supérieur à 5, emparez-vous de l'arme. Les effets de ce Lieu sera annulé pour vous jusqu'à la fin de la partie.

Tous les points ont été corrigés, je ferme l'issue.
