### ISSUE TITLE
[Harry Potter] Equipements

### ISSUE THREAD

**Issue by SuceMaLicorne** [Volminoduro/le-compendium#5]
# 1. Accessoires
### 1.2.2. Miss Teigne (1 exemplaire)
Regard perçant : Annule les malus de portée d’un adversaire de combat s’il est à 1 de portée ou moins de vous.
 > Mécanique pas assez utilisée.

### 1.2.4. Marque des Ténèbres (2 Exemplaires)
> Mécanique super cool
> Défaussable si pas équipée

### 1.2.5. Pièce de l’Armée de Dumbledore (3 exemplaires)
> Trouver une mécanique sur autre chose pour que les neutres ailles vers les antagonistes. 

### 1.2.6. Nimbus 2001 (1 exemplaire)
Vous pouvez vous déplacer jusqu’à deux cases, dans le sens que vous voulez, au lieu de lancer les dés.
> Trop craqué ? Proposer que deux cases plutôt que 1 à 2 ?

### 1.3.1. Nagini (1 exemplaire)
Venin : Les blessures de combat que vous infligez baissent également les Blessures maximums, se limite à [X] effets par cible.
> Caper le max de stack venin.

### 1.3.2. Sombral (1 exemplaire)
> Super cool.

### 1.3.4. Main de la gloire (1 exemplaire)
> Reformuler peut être pour la poudre du Pérou.

## 1.4. Légendaire
> Peut être équipé avec la (Pierre de Résurrection)la Baguette et la Cape d’Invisibilité.

# 2. Armes
### 2.1.1. Arbalète de Rubeus Hagrid (1 exemplaire)
+2 de portée.
> Opé ? à tester en game.

### 2.2.1. Bois d’hêtre, 35,1 centimètres, plume de phénix (1 exemplaire)
Maîtrise : si vous avez bénéficier 3 fois de l’effet Favorable à l’indécision ou 5 fois de l'Initiative, votre bonus d'Initiative passe à 2 d’attaque et de défense au lieu de 1, et l’ancienneté de l’attaque peut remonter à 2 tours. Votre bonus de Favorable à l’indécision passe à 2 d’attaque.
>Difficulté à compter / se souvenir.

Maîtrise : après détruit un accessoire adverse disposant de la compétence Compagnon, votre bonus de Spécisme passe à 2 d’attaque et de défense au lieu de 1.
> Mot manquant en début de phrase ?

### 2.2.3. Bois d’érable, 41,8 centimètres, plume d’oiseau-tonnerre (1 exemplaire)
Maîtrise : après vous êtes défendu 3 fois avec succès ou après avoir visité 3 Lieux différents, votre bonus d'Explorateur passe à 3 d’attaque et de défense au lieu de 2 et cela fonctionne à une case adjacente de la case Lieux. L’effet Vigilance vous permet désormais également de contre-attaquer l’adversaire.
>Difficulté à compter / se souvenir.

### 2.3.1. Bois de prunellier, 26 centimètres, poil de Rougarou (1 exemplaire)
Maîtrise : après avoir blessé au moins la moitié des autres joueurs toujours en vie, votre bonus de Belliqueuse passe à 2 d’attaque au lieu de 1. Vous disposez désormais d’un bonus de défense de 2 en vous défendant contre un joueur que vous avez blessé.
>Difficulté à compter / se souvenir.
> La moitié des joueurs. Peut être un peu compliqué de mise en place. 
> Revoir le bonus de dégâts à la hausse ? Ou Creshendo +1 à chaque nouvelle cible, supprime le possible soucis de compter "la moitié" et des impaires. 

### 2.3.2. Bois d’if, 29,1 centimètres, ventricule de dragon (1 exemplaire)
Bourreau : +1 d’attaque contre les personnages au seuil de la mort.
> Arrive suffisamment rarement, buff à la hausse pour donner un réel intérêt à la baguette ? 
Pourquoi choisir celle ci plutôt qu'une autre qui donne cet affet perma avec d'autres bonus ?

### 2.3.3. Bois de tilleul argenté, 21,9 centimètres, corne de Serpent cornu (1 exemplaire)
Affinité envers la Legilimency : si une attaque à un autre personnage lui inflige des blessures, il doit vous révéler sa main.
> Cool comme mécanique - Jouer sur des effets hors combat comme celui ci.
Détection serpentine : pendant leur tour, les autres joueurs se déplaçant à une case de vous déclenche les mêmes effets de détection que le Miroir à l’ennemi.

### 2.4.1. Baguette de sureau (1 exemplaire)
> Peut on perdre avec cet objet ?

### 2.4.2. Epée de Godric Griffondor (1 exemplaire)
> Manque pas un petit quelque chose ?

# 3. Corps
### 3.1.1 Manteau bouclier
> Nom = Cape d'une maison ? (Pas intéressant de faire les 4)
> Effet -> Selon le background de la maison ?

## 3.4. Légendaire
> [Résister aux effets négatifs ?] déjà craqué, à voir ce que tu veux add. 

# 4. Tête
### 4.1.1. Lorgnospectres (2 exemplaires)
Détecteur de Joncheruine : vous pouvez voir les joncheruines autour de la tête des personnages. Cela ne sert à rien.
>Ajouter un effet autre que la détection de cape d'invisibilité. Un truc qui proc que rarement ou/et sous certaines conditions. Un mini bonus.

### 4.3.2. Choixpeau magique (1 exemplaire)
Legilimancie chapelière (2 charges d’utilisation) : Le joueur ciblé doit indiqué son identité et sa quête aux autres joueurs. Il peut lancez les deux dés, s’il fait au moins 5, il aura le droit de mentir.
> Une charge ? Deux c'est peut être trop ?

**Comment by Volminoduro** [comment]
# 1. Accessoires
## 1.2. Rare
### 1.2.2. Miss Teigne (1 exemplaire) (TODO)
Regard perçant : Annule les malus de portée d’un adversaire de combat s’il est à 1 de portée ou moins de vous.
 > Mécanique pas assez utilisée.

### 1.2.4. Marque des Ténèbres (2 Exemplaires) (DONE)
> Mécanique super cool
> Défaussable si pas équipée

Texte ajouté.

### 1.2.5. Pièce de l’Armée de Dumbledore (3 exemplaires) (TODO)
> Trouver une mécanique sur autre chose pour que les neutres ailles vers les antagonistes. => 

### 1.2.6. Nimbus 2001 (1 exemplaire) (DONE)
Vous pouvez vous déplacer jusqu’à deux cases, dans le sens que vous voulez, au lieu de lancer les dés.
> Trop craqué ? Proposer que deux cases plutôt que 1 à 2 ?
Oui, je trouve cela aussi intéressant car cela limite ton champ des possibles et peut te pousser à choisir entre tous les balais. Pareil pour l'éclair de feu suprême, cela te déplace que de 3 cases.

## 1.3. Epique
### 1.3.1. Nagini (1 exemplaire) (DONE)
Venin : Les blessures de combat que vous infligez baissent également les Blessures maximums, se limite à [X] effets par cible.
> Caper le max de stack venin.

Pas de cap pour le moment puisque il faudra beta tester, et que ça peut être une raison pour les joueurs de focus un autre.

### 1.3.4. Main de la gloire (1 exemplaire) (DONE)
> Reformuler peut être pour la poudre du Pérou.

Reformulé pour : Lorsque vous attaquez un autre personnage, la _Poudre d'Obscurité Instantanée du Pérou_ ne pourra lui faire fuir le combat.

## 1.4. Légendaire (DONE)
> Peut être équipé avec la (Pierre de Résurrection)la Baguette et la Cape d’Invisibilité.

Corrigé.

# 2. Armes

## 2.2. Rare
### 2.2.1. Bois d’hêtre, 35,1 centimètres, plume de phénix (1 exemplaire) (TODO)
Maîtrise : si vous avez bénéficier 3 fois de l’effet Favorable à l’indécision ou 5 fois de l'Initiative, votre bonus d'Initiative passe à 2 d’attaque et de défense au lieu de 1, et l’ancienneté de l’attaque peut remonter à 2 tours. Votre bonus de Favorable à l’indécision passe à 2 d’attaque.
>Difficulté à compter / se souvenir.

Maîtrise : après détruit un accessoire adverse disposant de la compétence Compagnon, votre bonus de Spécisme passe à 2 d’attaque et de défense au lieu de 1.
> Mot manquant en début de phrase ?

### 2.2.3. Bois d’érable, 41,8 centimètres, plume d’oiseau-tonnerre (1 exemplaire) (TODO)
Maîtrise : après vous êtes défendu 3 fois avec succès ou après avoir visité 3 Lieux différents, votre bonus d'Explorateur passe à 3 d’attaque et de défense au lieu de 2 et cela fonctionne à une case adjacente de la case Lieux. L’effet Vigilance vous permet désormais également de contre-attaquer l’adversaire.
>Difficulté à compter / se souvenir.

## 2.3. Epique
### 2.3.1. Bois de prunellier, 26 centimètres, poil de Rougarou (1 exemplaire) (TODO)
Maîtrise : après avoir blessé au moins la moitié des autres joueurs toujours en vie, votre bonus de Belliqueuse passe à 2 d’attaque au lieu de 1. Vous disposez désormais d’un bonus de défense de 2 en vous défendant contre un joueur que vous avez blessé.
>Difficulté à compter / se souvenir.
> La moitié des joueurs. Peut être un peu compliqué de mise en place. => Moitié des joueurs en vie, donc c'est de plus en plus facile plus y'a de mort, ce que favorise la baguette avec un gameplay très aggressifs.
> Revoir le bonus de dégâts à la hausse ? Ou Creshendo +1 à chaque nouvelle cible, supprime le possible soucis de compter "la moitié" et des impaires. 

### 2.3.2. Bois d’if, 29,1 centimètres, ventricule de dragon (1 exemplaire) (TODO)
Bourreau : +1 d’attaque contre les personnages au seuil de la mort.
> Arrive suffisamment rarement, buff à la hausse pour donner un réel intérêt à la baguette ? 
Pourquoi choisir celle ci plutôt qu'une autre qui donne cet affet perma avec d'autres bonus ?

### 2.3.3. Bois de tilleul argenté, 21,9 centimètres, corne de Serpent cornu (1 exemplaire) (TODO)
Affinité envers la Legilimency : si une attaque à un autre personnage lui inflige des blessures, il doit vous révéler sa main.
> Cool comme mécanique - Jouer sur des effets hors combat comme celui ci.
Détection serpentine : pendant leur tour, les autres joueurs se déplaçant à une case de vous déclenche les mêmes effets de détection que le Miroir à l’ennemi.

## 2.4. Légendaire
### 2.4.1. Baguette de sureau (1 exemplaire) (TODO)
> Peut on perdre avec cet objet ?

### 2.4.2. Epée de Godric Griffondor (1 exemplaire) (TODO)
> Manque pas un petit quelque chose ?

# 3. Corps
## 3.4. Légendaire (TODO)
> [Résister aux effets négatifs ?] déjà craqué, à voir ce que tu veux add. 

# 4. Tête
## 4.1. Commune
### 4.1.1. Lorgnospectres (2 exemplaires) (DONE)
Détecteur de Joncheruine : vous pouvez voir les joncheruines autour de la tête des personnages. Cela ne sert à rien.
>Ajouter un effet autre que la détection de cape d'invisibilité. Un truc qui proc que rarement ou/et sous certaines conditions. Un mini bonus.

=> je osuhaite que ça soit vraiment un objet de niche. Donc, il faut qu'il reste complètement inutile SAUF dans un cas précis, qui lui est pourtant celui d'un objet très puissant. 

## 4.3. Epique
### 4.3.2. Choixpeau magique (1 exemplaire) (DONE)
Legilimancie chapelière (2 charges d’utilisation) : Le joueur ciblé doit indiqué son identité et sa quête aux autres joueurs. Il peut lancez les deux dés, s’il fait au moins 5, il aura le droit de mentir.
> Une charge ? Deux c'est peut être trop ? => Deux charges sont pour éviter que le chapeau se défausse dès la premièrer utilisation.

**Comment by Volminoduro** [comment]
# 1. Accessoires
## 1.2. Rare
### 1.2.2. Miss Teigne (1 exemplaire) (TODO)
Regard perçant : Annule les malus de portée d’un adversaire de combat s’il est à 1 de portée ou moins de vous.
 > Mécanique pas assez utilisée.

### 1.2.5. Pièce de l’Armée de Dumbledore (3 exemplaires) (TODO)
> Trouver une mécanique sur autre chose pour que les neutres ailles vers les antagonistes. => 

# 2. Armes

## 2.2. Rare
### 2.2.1. Bois d’hêtre, 35,1 centimètres, plume de phénix (1 exemplaire) (DONE)
Maîtrise : si vous avez bénéficier 3 fois de l’effet Favorable à l’indécision ou 5 fois de l'Initiative, votre bonus d'Initiative passe à 2 d’attaque et de défense au lieu de 1, et l’ancienneté de l’attaque peut remonter à 2 tours. Votre bonus de Favorable à l’indécision passe à 2 d’attaque.
>Difficulté à compter / se souvenir.

si vous avez bénéficié 4 fois de l'effet _Favorable à l'indécision_ et / ou l'_Initiative_ (les deux se cumulant). C'est un peu plus facile, il faudra que je réfléchisse à un système de jetons éventuellement.

Maîtrise : après détruit un accessoire adverse disposant de la compétence Compagnon, votre bonus de Spécisme passe à 2 d’attaque et de défense au lieu de 1.
> Mot manquant en début de phrase ?

Corrigé.

### 2.2.3. Bois d’érable, 41,8 centimètres, plume d’oiseau-tonnerre (1 exemplaire) (DONE)
Maîtrise : après vous êtes défendu 3 fois avec succès ou après avoir visité 3 Lieux différents, votre bonus d'Explorateur passe à 3 d’attaque et de défense au lieu de 2 et cela fonctionne à une case adjacente de la case Lieux. L’effet Vigilance vous permet désormais également de contre-attaquer l’adversaire.
>Difficulté à compter / se souvenir.

Je ne trouve pas si difficile, mais il faudra le noter.

## 2.3. Epique
### 2.3.1. Bois de prunellier, 26 centimètres, poil de Rougarou (1 exemplaire) (DONE)
Maîtrise : après avoir blessé au moins la moitié des autres joueurs toujours en vie, votre bonus de Belliqueuse passe à 2 d’attaque au lieu de 1. Vous disposez désormais d’un bonus de défense de 2 en vous défendant contre un joueur que vous avez blessé.
>Difficulté à compter / se souvenir.
> La moitié des joueurs. Peut être un peu compliqué de mise en place. => Moitié des joueurs en vie, donc c'est de plus en plus facile plus y'a de mort, ce que favorise la baguette avec un gameplay très aggressifs.
> Revoir le bonus de dégâts à la hausse ? Ou Creshendo +1 à chaque nouvelle cible, supprime le possible soucis de compter "la moitié" et des impaires. 

Pour la moitié avec les impairs, j'ai indiqué la moitié supérieure. Ensuite, le bonus de dégâts a été remanié : Vous débloquez aussi l'effet *Furie sanguinaire :* vous avez actuellement +1 d'attaque pour chaque joueur encore en vie que vous avez blessé dans la partie.

C'est très puissant à bcp de joueurs et sa puissance baisse au fur et à mesure des morts.

### 2.3.2. Bois d’if, 29,1 centimètres, ventricule de dragon (1 exemplaire) (DONE)
Bourreau : +1 d’attaque contre les personnages au seuil de la mort.
> Arrive suffisamment rarement, buff à la hausse pour donner un réel intérêt à la baguette ? 
Pourquoi choisir celle ci plutôt qu'une autre qui donne cet affet perma avec d'autres bonus ?

Nouvelle capacité en plus :
Vous débloquez également la compétence *Moissoneur de vie :* tous les deux personnages que vous avez achevé définitivement vous confère +1 d'attaque et de défense (mettez leurs cartes _Personnages_ en dessous de la votre).
Donc en gros, tu tues une personne pour avoir la maitrise, et une deuxième pour ce bonus là. C'est assez peu utile à 3 joueurs. Mais, en même temps, à 3 joueurs, y'a plus d'arme à brasser donc tu peux te diriger vers d'autres armes.

### 2.3.3. Bois de tilleul argenté, 21,9 centimètres, corne de Serpent cornu (1 exemplaire) (DONE)
Affinité envers la Legilimency : si une attaque à un autre personnage lui inflige des blessures, il doit vous révéler sa main.
> Cool comme mécanique - Jouer sur des effets hors combat comme celui ci.
Détection serpentine : pendant leur tour, les autres joueurs se déplaçant à une case de vous déclenche les mêmes effets de détection que le Miroir à l’ennemi.

## 2.4. Légendaire
### 2.4.1. Baguette de sureau (1 exemplaire) (DONE)
> Peut on perdre avec cet objet ?

D'autres baguettes sont plus fortes situationnellement, celle là est surtout très fiable.

### 2.4.2. Epée de Godric Griffondor (1 exemplaire) (DONE)
> Manque pas un petit quelque chose ?

Bonus de +1 d'attaque passé à +2 d'attaque et +1 de défense.

Désormais, tu brises l'équipement adverse de ton choix pour en avoir les bonus, au lieu de juste l'arme adverse, cela peut permettre de OS les Compagnon par exemple.

# 3. Corps
## 3.4. Légendaire (DONE)
> [Résister aux effets négatifs ?] déjà craqué, à voir ce que tu veux add. 

* *[Nom] :* Vous ne pouvez être la cible d'effets directs vous infligeant des blessures de la part d'autres joueurs (charges d'équipements, consommables, capacités de personnages, etc.).

Pour le moment. A peaufiner éventuellement.

**Comment by Volminoduro** [comment]
# 1. Accessoires
## 1.2. Rare
### 1.2.2. Miss Teigne (1 exemplaire) (DONE)
Regard perçant : Annule les malus de portée d’un adversaire de combat s’il est à 1 de portée ou moins de vous.
 > Mécanique pas assez utilisée, c'est plus utilisé avec les personnages rajoutées.

### 1.2.5. Pièce de l’Armée de Dumbledore (3 exemplaires) (DONE)
> Trouver une mécanique sur autre chose pour que les neutres ailles vers les antagonistes. => 

Pas trouvé pour le moment, à voir si c'est si impactant que ça.
